server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth, /auth/**, /login, /register,/logout, /users/**, /user-css/**, /user-js/**,/home/**,/profile/**,/update-profile,/update-email,/update-password,/currentUser

        - id: book-service
          uri: http://localhost:8083
          predicates:
            - Path=/books/**,/BooksAvailable/**,/book-css/**,/book-js/**

        - id: admine-service
          uri: http://localhost:8084
          predicates:
            - Path=/usersDashbord ,/booksDashbord ,/addBook,/deleteBook/**,/updateBook,/editBook/**,/admine-css/**
                    
      

        

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
