server:
  port: 8084

spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:mysql://localhost:3306/booknet_loans
    username: root
    password: yasser331790
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
